### ISSUE TITLE
Main task for spring

### ISSUE THREAD

**Issue by VasilevSaryal** [team-dev-spring-2022/TGBot#33]
**Основная задача:** сделать Telegram Bot для упрощения процесса учебы.

### Этап 0

- [ ] Сделать пустой проект @VasilevSaryal
- [ ] Оформить README.md #1 @Bopemt 
- [ ] Создать и настроить Telegram Bot через BotFather #9 @fedniko 
- [ ] Добавить первую команду `/help` #2 @PetrovEgor 
- [ ] Добавить 0pdd линтовку для мониторинга деятельности программиста #4  @VasilevSaryal 
- [ ] Настроить Github Actions #16 @Bopemt 

### Этап 1

- [ ] Сделать напоминалку в TGBot, что необходимо сделать изменения в Google Calendar или Trello #3 @fedniko 
- [ ] Добавить PyLint в Github Actions #29 @Bopemt 
- [ ] Добавить Build Server в TGBot #30 @PetrovEgor 
- [ ] Мониторинг напоминалки TGBot #31 @fedniko 
- [ ] Добавить распределим ответственности за внесения изменений в Google Calendar и Trello #32 @fedniko
